### ISSUE TITLE
Invalid plugin version number

### ISSUE THREAD

**Issue by Klumbumbus** [BjornRasmussen/Lanes#3]
See https://josm.openstreetmap.de/ticket/20067

**Comment by BjornRasmussen** [comment]
Fixed.  This will update in the plugin list 10 min after the next release.

**Comment by BjornRasmussen** [comment]
Hmm, this is still not working...

**Comment by Klumbumbus** [comment]
It works now.

**Comment by joshinils** [comment]
well, it's like that for me now
<img width="728" height="122" alt="Image" src="https://github.com/user-attachments/assets/c11e6937-e089-4ffe-95c7-162c25a7bc1c" />

```console
$ flatpak run org.openstreetmap.josm --version
Using /app/jre/bin/java to execute josm.
JOSM/1.5 (19555 en) Linux Freedesktop SDK 25.08 (Flatpak runtime)
```
